import { env } from "../config/env";

interface YouTubeVideoResponse {
  items?: Array<{
    id: string;
    snippet?: {
      title?: string;
      description?: string;
      channelTitle?: string;
    };
  }>;
}

export interface YouTubeContent {
  title: string;
  description: string;
  channelTitle: string;
  content: string;
}

export async function getYouTubeVideo(
  videoId: string
) {
  const apiKey = env.youtubeApiKey;

  if (!apiKey) {
    throw new Error(
      "YOUTUBE_API_KEY is not configured."
    );
  }

  const url =
    "https://www.googleapis.com/youtube/v3/videos" +
    `?part=snippet&id=${encodeURIComponent(videoId)}` +
    `&key=${encodeURIComponent(apiKey)}`;

  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(
      `YouTube API request failed: ${response.status}`
    );
  }

  const data =
    (await response.json()) as YouTubeVideoResponse;

  const video = data.items?.[0];

  if (!video) {
    throw new Error(
      "YouTube video could not be found."
    );
  }

  return {
    id: video.id,
    title:
      video.snippet?.title ??
      "YouTube video",
    description:
      video.snippet?.description ??
      "",
    channelTitle:
      video.snippet?.channelTitle ??
      "",
  };
}

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
}

class YouTubeTranscriptDisabledError extends Error {}
class YouTubeTranscriptEmptyError extends Error {}

// Matches YouTube's standard timed-text XML format.
const RE_XML_TRANSCRIPT =
  /<text start="([^"]*)" dur="([^"]*)">([^<]*)<\/text>/g;

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");
}

async function fetchCaptionTracks(
  videoId: string,
  lang: string
): Promise<CaptionTrack[]> {
  const response = await fetch(
    "https://www.youtube.com/youtubei/v1/player",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "User-Agent":
          "com.google.android.youtube/19.09.37 (Linux; Android 13)",
      },
      body: JSON.stringify({
        context: {
          client: {
            clientName: "ANDROID",
            clientVersion: "19.09.37",
            androidSdkVersion: 33,
            hl: lang,
            gl: "US",
          },
        },
        videoId,
      }),
    }
  );

  if (!response.ok) {
    throw new Error(
      `YouTube InnerTube request failed: ${response.status}`
    );
  }

  const data = (await response.json()) as {
    captions?: {
      playerCaptionsTracklistRenderer?: {
        captionTracks?: CaptionTrack[];
      };
    };
  };

  const tracks =
    data.captions?.playerCaptionsTracklistRenderer
      ?.captionTracks;

  if (!tracks || tracks.length === 0) {
    throw new YouTubeTranscriptDisabledError(
      `No caption tracks available for video ${videoId}.`
    );
  }

  return tracks;
}

function pickTrack(
  tracks: CaptionTrack[],
  lang: string
): CaptionTrack {
  const exact = tracks.find(
    (track) =>
      track.languageCode === lang ||
      track.languageCode.startsWith(`${lang}-`)
  );

  if (exact) {
    return exact;
  }

  const autoGenerated = tracks.find(
    (track) => track.kind === "asr"
  );

  return autoGenerated ?? tracks[0];
}

async function fetchTranscriptSnippets(
  videoId: string,
  lang = "en"
): Promise<Array<{ text: string }>> {
  const tracks = await fetchCaptionTracks(
    videoId,
    lang
  );

  const track = pickTrack(tracks, lang);

  const transcriptResponse = await fetch(
    track.baseUrl,
    {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      },
    }
  );

  if (!transcriptResponse.ok) {
    throw new YouTubeTranscriptEmptyError(
      `Transcript track request failed for video ${videoId}.`
    );
  }

  const body = await transcriptResponse.text();

  const matches = [
    ...body.matchAll(RE_XML_TRANSCRIPT),
  ];

  const snippets = matches
    .map((match) => ({
      text: decodeHtmlEntities(match[3] ?? ""),
    }))
    .filter((snippet) => snippet.text.trim() !== "");

  if (snippets.length === 0) {
    throw new YouTubeTranscriptEmptyError(
      `No transcript text found for video ${videoId}.`
    );
  }

  return snippets;
}

export async function extractYouTubeContent(
  videoId: string
): Promise<YouTubeContent> {
  const video =
    await getYouTubeVideo(videoId);

  let snippets;

  try {
    snippets =
      await fetchTranscriptSnippets(videoId);
  } catch (error) {
    console.error(
      `[YouTube Transcript] Fetch failed for video ${videoId}:`,
      error
    );

    if (
      error instanceof
      YouTubeTranscriptDisabledError
    ) {
      throw new Error(
        "This YouTube video has no captions available."
      );
    }

    if (
      error instanceof
      YouTubeTranscriptEmptyError
    ) {
      throw new Error(
        "Could not read the transcript for this YouTube video. Please try again."
      );
    }

    throw new Error(
      "Failed to fetch this YouTube video's transcript. Please try again."
    );
  }

  const content = snippets
    .map((snippet) => snippet.text)
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();

  if (!content) {
    throw new Error(
      "No transcript was found for this YouTube video."
    );
  }

  return {
    title: video.title,
    description: video.description,
    channelTitle: video.channelTitle,
    content,
  };
}